import { cssQueriesConfig } from "@/css/queries-config/index.ts";
import fullCSSSyntax from "@/css/syntax-config/variations/full.ts";

export default cssQueriesConfig(fullCSSSyntax, [
  "@media (width < 480px)",
  "@media (480px <= width < 768px)",
  "@media (768px <= width < 1024px)",
  "@media (width >= 1024px)",
  "@media (height >= 600px)",
  "@media (orientation: landscape)",
  "@media (orientation: portrait)",
  "@media (prefers-color-scheme: light)",
  "@media (prefers-color-scheme: dark)",
  "@media (prefers-reduced-motion: reduce)",
  "@media (prefers-reduced-motion: no-preference)",
  "@media (resolution >= 2dppx)",
  "@media (min-device-pixel-ratio: 2)",
  "@media (min-resolution: 2dppx)",
  "@media screen and (width < 768px)",
  "@media only screen and (width >= 1024px)",
  "@media not print",
  "@media print",
  "@media all",
  "@media (width < 768px), (orientation: portrait)",
  "@media (width < 768px) and (prefers-color-scheme: dark)",
  "@container (width > 400px)",
  "@container sidebar (min-width: 600px)",
  "@container (width > 400px) and (height > 200px)",
  "@container (400px < width <= 800px)",
  "@container style(--theme: dark)",
  "@container sidebar style(--theme: dark)",
]);