import { SUPPORTED_KEYWORDS } from "tsyntax";
import { htmlTagConfig } from "@/html/tag-config/index.ts";
import CSS_ATTRIBUTES_CONFIG from "@/css/attribute-config/variations/common.ts";

export default htmlTagConfig(SUPPORTED_KEYWORDS, CSS_ATTRIBUTES_CONFIG, {
  a: {
    display: "inline",
    attributes: {
      href: "string",
      target: "'_self' | '_blank' | '_parent' | '_top' | undefined",
      download: "string | boolean | undefined",
      rel: "string | undefined",
      hreflang: "string | undefined",
    },
    innerHTML: [
      "#text",
      "img",
      "div",
      "section",
      "p",
      "ul",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "span",
      "br",
    ],
    cssPseudoClass: [":link", ":visited", ":any-link"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  article: {
    display: "block",
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  br: {
    display: "inline",
    attributes: {},
    innerHTML: [],
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  button: {
    display: "inline-block",
    attributes: {
      type: "'submit' | 'reset' | 'button' | undefined",
      disabled: "boolean | undefined",
      name: "string | undefined",
      value: "string | undefined",
      form: "string | undefined",
    },
    innerHTML: ["#text", "span", "img", "br"],
    cssPseudoClass: [":disabled", ":enabled"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  div: {
    display: "block",
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  footer: {
    display: "block",
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  form: {
    display: "block",
    attributes: {
      action: "string | undefined",
      method: "'get' | 'post' | 'dialog'",
      enctype: "string | undefined",
      novalidate: "boolean | undefined",
      target: "'_self' | '_blank' | '_parent' | '_top' | undefined",
    },
    innerHTML: "*",
    cssPseudoClass: [":valid", ":invalid"],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h1: {
    display: "block",
    attributes: {},
    innerHTML: ["#text", "span", "a", "br", "img"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h2: {
    display: "block",
    attributes: {},
    innerHTML: ["#text", "span", "a", "br", "img"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h3: {
    display: "block",
    attributes: {},
    innerHTML: ["#text", "span", "a", "br", "img"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h4: {
    display: "block",
    attributes: {},
    innerHTML: ["#text", "span", "a", "br", "img"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h5: {
    display: "block",
    attributes: {},
    innerHTML: ["#text", "span", "a", "br", "img"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h6: {
    display: "block",
    attributes: {},
    innerHTML: ["#text", "span", "a", "br", "img"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  header: {
    display: "block",
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  img: {
    display: "inline",
    attributes: {
      src: "string",
      alt: "string",
      width: "number | undefined",
      height: "number | undefined",
      loading: "'lazy' | 'eager' | undefined",
      srcset: "string | undefined",
      sizes: "string | undefined",
    },
    innerHTML: [],
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  input: {
    display: "inline-block",
    attributes: {
      type: "'text' | 'number' | 'password' | 'checkbox' | 'radio' | 'submit' | 'button' | 'email' | 'hidden'",
      value: "string | undefined",
      checked: "boolean | undefined",
      name: "string | undefined",
      placeholder: "string | undefined",
      disabled: "boolean | undefined",
      required: "boolean | undefined",
      readonly: "boolean | undefined",
      maxlength: "number | undefined",
      minlength: "number | undefined",
      max: "string | number | undefined",
      min: "string | number | undefined",
      step: "string | number | undefined",
      pattern: "string | undefined",
      hidden: "boolean | undefined",
    },
    innerHTML: [],
    cssPseudoClass: [
      ":disabled",
      ":enabled",
      ":checked",
      ":valid",
      ":invalid",
      ":required",
      ":optional",
      ":placeholder-shown",
    ],
    cssPseudoElement: ["::placeholder", "::file-selector-button"],
  },
  label: {
    display: "inline",
    attributes: {
      for: "string | undefined",
      form: "string | undefined",
    },
    innerHTML: ["#text", "a", "input", "span", "img", "br"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  li: {
    display: "list-item",
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
      "::marker",
    ],
  },
  main: {
    display: "block",
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  nav: {
    display: "block",
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  ol: {
    display: "block",
    attributes: {},
    innerHTML: ["li"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  p: {
    display: "block",
    attributes: {},
    innerHTML: ["#text", "span", "a", "img", "input", "br", "label"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  section: {
    display: "block",
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  span: {
    display: "inline",
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  table: {
    display: "table",
    attributes: {},
    innerHTML: ["thead", "tbody", "tr"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  tbody: {
    display: "table-row-group",
    attributes: {},
    innerHTML: ["tr"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  td: {
    display: "table-cell",
    attributes: {
      colspan: "number | undefined",
      rowspan: "number | undefined",
      headers: "string | undefined",
    },
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  textarea: {
    display: "inline-block",
    attributes: {
      name: "string | undefined",
      placeholder: "string | undefined",
      rows: "number | undefined",
      cols: "number | undefined",
      disabled: "boolean | undefined",
      required: "boolean | undefined",
      readonly: "boolean | undefined",
      maxlength: "number | undefined",
    },
    innerHTML: ["#text"],
    cssPseudoClass: [
      ":disabled",
      ":enabled",
      ":valid",
      ":invalid",
      ":required",
      ":optional",
      ":placeholder-shown",
    ],
    cssPseudoElement: ["::placeholder"],
  },
  th: {
    display: "table-cell",
    attributes: {
      colspan: "number | undefined",
      rowspan: "number | undefined",
      headers: "string | undefined",
    },
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  thead: {
    display: "table-header-group",
    attributes: {},
    innerHTML: ["tr"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  tr: {
    display: "table-row",
    attributes: {},
    innerHTML: ["th", "td"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  ul: {
    display: "block",
    attributes: {},
    innerHTML: ["li"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
});

// lsp-touch
