import { SUPPORTED_KEYWORDS } from "tsyntax";
import { htmlTagConfig } from "@/html/tag-config/index.ts";
import CSS_ATTRIBUTES_CONFIG from "@/css/attribute-config/variations/common.ts";

export default htmlTagConfig(SUPPORTED_KEYWORDS, CSS_ATTRIBUTES_CONFIG, {
  a: {
    display: "inline",
    attributes: {
      href: "`https://${string}` | `http://${string}` | `mailto:${string}` | `tel:${string}` | `./${string}` | `/${string}`",
      target: "'_self' | '_blank' | '_parent' | '_top' | undefined",
      download: "string | boolean | undefined",
      rel: "string | undefined",
      hreflang: "string | undefined",
    },
    innerHTML: {
      include: [
        "#text",
        "img",
        "div",
        "section",
        "p",
        "ul",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "span",
        "br",
      ],
    },
    cssPseudoClass: [":link", ":visited", ":any-link"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  article: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  br: {
    display: "inline",
    attributes: {},
    innerHTML: { include: [] },
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  button: {
    display: "inline-block",
    attributes: {
      type: {
        submit: {
          formaction: "string | undefined",
          formenctype:
            "'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain' | undefined",
          formmethod: "'get' | 'post' | 'dialog' | undefined",
          formnovalidate: "boolean | undefined",
          formtarget: "'_self' | '_blank' | '_parent' | '_top' | undefined",
        },
        reset: {},
        button: {},
        undefined: {
          formaction: "string | undefined",
          formenctype:
            "'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain' | undefined",
          formmethod: "'get' | 'post' | 'dialog' | undefined",
          formnovalidate: "boolean | undefined",
          formtarget: "'_self' | '_blank' | '_parent' | '_top' | undefined",
        },
      },
      disabled: "boolean | undefined",
      name: "string | undefined",
      value: "string | undefined",
      form: "string | undefined",
    },
    innerHTML: { include: ["#text", "span", "img", "br"] },
    cssPseudoClass: [":disabled", ":enabled"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  div: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  footer: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  form: {
    display: "block",
    attributes: {
      action: "string | undefined",
      method: {
        get: {
          target: "'_self' | '_blank' | '_parent' | '_top' | undefined",
          novalidate: "boolean | undefined",
        },
        post: {
          enctype: "string | undefined",
          target: "'_self' | '_blank' | '_parent' | '_top' | undefined",
          novalidate: "boolean | undefined",
        },
        dialog: {},
      },
    },
    innerHTML: { all: true },
    cssPseudoClass: [":valid", ":invalid"],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h1: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["#text", "span", "a", "br", "img"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h2: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["#text", "span", "a", "br", "img"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h3: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["#text", "span", "a", "br", "img"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h4: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["#text", "span", "a", "br", "img"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h5: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["#text", "span", "a", "br", "img"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h6: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["#text", "span", "a", "br", "img"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  header: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  img: {
    display: "inline",
    attributes: {
      src: "`https://${string}` | `http://${string}` | `mailto:${string}` | `tel:${string}` | `./${string}` | `/${string}`",
      alt: "string",
      width: "number | undefined",
      height: "number | undefined",
      loading: "'lazy' | 'eager' | undefined",
      srcset: "string | undefined",
      sizes: "string | undefined",
    },
    innerHTML: { include: [] },
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  input: {
    display: "inline-block",
    attributes: {
      type: {
        text: {
          maxlength: "number | undefined",
          minlength: "number | undefined",
          pattern: "string | undefined",
        },
        number: {
          min: "string | number | undefined",
          max: "string | number | undefined",
          step: "string | number | undefined",
        },
        password: {
          maxlength: "number | undefined",
          minlength: "number | undefined",
          pattern: "string | undefined",
        },
        checkbox: { checked: "boolean | undefined" },
        radio: { checked: "boolean | undefined" },
        email: {
          maxlength: "number | undefined",
          minlength: "number | undefined",
          pattern: "string | undefined",
        },
        submit: {},
        button: {},
        hidden: {},
      },
      value: "string | undefined",
      name: "string | undefined",
      placeholder: "string | undefined",
      disabled: "boolean | undefined",
      required: "boolean | undefined",
      readonly: "boolean | undefined",
      hidden: "boolean | undefined",
    },
    innerHTML: { include: [] },
    cssPseudoClass: [
      ":disabled",
      ":enabled",
      ":checked",
      ":valid",
      ":invalid",
      ":required",
      ":optional",
      ":placeholder-shown",
    ],
    cssPseudoElement: ["::placeholder", "::file-selector-button"],
  },
  label: {
    display: "inline",
    attributes: {
      for: "string | undefined",
      form: "string | undefined",
    },
    innerHTML: { include: ["#text", "a", "input", "span", "img", "br"] },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  li: {
    display: "list-item",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
      "::marker",
    ],
  },
  main: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  nav: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  ol: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["li"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  p: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["#text", "span", "a", "img", "input", "br", "label"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  section: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  span: {
    display: "inline",
    attributes: {},
    innerHTML: { include: ["#text", "a", "span", "img", "br", "input"] },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  table: {
    display: "table",
    attributes: {},
    innerHTML: { include: ["thead", "tbody", "tr"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  tbody: {
    display: "table-row-group",
    attributes: {},
    innerHTML: { include: ["tr"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  td: {
    display: "table-cell",
    attributes: {
      colspan: "number | undefined",
      rowspan: "number | undefined",
      headers: "string | undefined",
    },
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  textarea: {
    display: "inline-block",
    attributes: {
      name: "string | undefined",
      placeholder: "string | undefined",
      rows: "number | undefined",
      cols: "number | undefined",
      disabled: "boolean | undefined",
      required: "boolean | undefined",
      readonly: "boolean | undefined",
      maxlength: "number | undefined",
    },
    innerHTML: { include: ["#text"] },
    cssPseudoClass: [
      ":disabled",
      ":enabled",
      ":valid",
      ":invalid",
      ":required",
      ":optional",
      ":placeholder-shown",
    ],
    cssPseudoElement: ["::placeholder"],
  },
  th: {
    display: "table-cell",
    attributes: {
      colspan: "number | undefined",
      rowspan: "number | undefined",
      headers: "string | undefined",
    },
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  thead: {
    display: "table-header-group",
    attributes: {},
    innerHTML: { include: ["tr"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  tr: {
    display: "table-row",
    attributes: {},
    innerHTML: { include: ["th", "td"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  ul: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["li"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
});

// lsp-touch
