import { SUPPORTED_KEYWORDS } from "tsyntax";
import { htmlTagConfig } from "@/html/tag-config/index.ts";
import CSS_ATTRIBUTES_CONFIG from "@/css/attribute-config/variations/full.ts";

export default htmlTagConfig(SUPPORTED_KEYWORDS, CSS_ATTRIBUTES_CONFIG, {
  a: {
    display: "inline",
    attributes: {
      href: "`https://${string}` | `http://${string}` | `mailto:${string}` | `tel:${string}` | `./${string}` | `/${string}`",
      target: "'_self' | '_blank' | '_parent' | '_top' | undefined",
      download: "string | boolean | undefined",
      rel: "string | undefined",
      hreflang: "string | undefined",
      ping: "string | undefined",
      referrerpolicy:
        "'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url' | undefined",
    },
    innerHTML: {
      include: [
        "#text",
        "div",
        "section",
        "p",
        "ul",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "img",
        "ins",
        "kbd",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [":link", ":visited", ":any-link", ":local-link"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  abbr: {
    display: "inline",
    attributes: {
      title: "string | undefined",
    },
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  address: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  b: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  bdi: {
    display: "inline",
    attributes: {
      dir: "'ltr' | 'rtl' | 'auto' | undefined",
    },
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  bdo: {
    display: "inline",
    attributes: {
      dir: "'ltr' | 'rtl'",
    },
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  blockquote: {
    display: "block",
    attributes: {
      cite: "string | undefined",
    },
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  br: {
    display: "inline",
    attributes: {},
    innerHTML: { include: [] },
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  cite: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  code: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  data: {
    display: "inline",
    attributes: {
      value: "string",
    },
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  dfn: {
    display: "inline",
    attributes: {
      title: "string | undefined",
    },
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  em: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  i: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  kbd: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  mark: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  q: {
    display: "inline",
    attributes: {
      cite: "string | undefined",
    },
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  rp: {
    display: "inline",
    attributes: {},
    innerHTML: { include: ["#text"] },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  rt: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  ruby: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
        "rp",
        "rt",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  s: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  samp: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  small: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  span: {
    display: "inline",
    attributes: {},
    innerHTML: { include: ["#text", "a", "span", "strong", "em", "img", "br", "input"] },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  strong: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  sub: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  sup: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  time: {
    display: "inline",
    attributes: {
      datetime: "string | undefined",
    },
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  u: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  var: {
    display: "inline",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  wbr: {
    display: "inline",
    attributes: {},
    innerHTML: { include: [] },
    cssPseudoClass: [],
    cssPseudoElement: [],
  },

  h1: {
    display: "block",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h2: {
    display: "block",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h3: {
    display: "block",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h4: {
    display: "block",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h5: {
    display: "block",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h6: {
    display: "block",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  hgroup: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["h1", "h2", "h3", "h4", "h5", "h6", "p"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },

  article: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  aside: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  details: {
    display: "block",
    attributes: {
      open: "boolean | undefined",
    },
    innerHTML: { include: ["summary", "div", "p", "ul", "ol", "table"] },
    cssPseudoClass: [":open"],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
      "::details-content",
    ],
  },
  dialog: {
    display: "block",
    attributes: {
      open: "boolean | undefined",
    },
    innerHTML: { all: true },
    cssPseudoClass: [":open", ":modal"],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
      "::backdrop",
    ],
  },
  div: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  footer: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  header: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  main: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  nav: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  p: {
    display: "block",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  search: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  section: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  summary: {
    display: "list-item",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "hgroup",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection", "::marker"],
  },

  dd: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  dl: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["dt", "dd", "div"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  dt: {
    display: "block",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  li: {
    display: "list-item",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
      "::marker",
    ],
  },
  menu: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["li"] },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  ol: {
    display: "block",
    attributes: {
      reversed: "boolean | undefined",
      start: "number | undefined",
      type: "'1' | 'a' | 'A' | 'i' | 'I' | undefined",
    },
    innerHTML: { include: ["li"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  ul: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["li"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },

  audio: {
    display: "inline",
    attributes: {
      src: "`https://${string}` | `http://${string}` | `./${string}` | `/${string}`",
      controls: "boolean | undefined",
      autoplay: "boolean | undefined",
      loop: "boolean | undefined",
      muted: "boolean | undefined",
      preload: "'none' | 'metadata' | 'auto' | undefined",
    },
    innerHTML: { include: ["source", "track"] },
    cssPseudoClass: [
      ":playing",
      ":paused",
      ":muted",
      ":volume-locked",
      ":seeking",
      ":buffering",
      ":stalled",
    ],
    cssPseudoElement: [],
  },
  canvas: {
    display: "inline",
    attributes: {
      width: "number | undefined",
      height: "number | undefined",
    },
    innerHTML: { include: ["#text"] },
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  figcaption: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  figure: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["img", "video", "audio", "canvas", "picture", "figcaption"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  iframe: {
    display: "inline",
    attributes: {
      src: "`https://${string}` | `http://${string}` | `./${string}` | `/${string}`",
      srcdoc: "string | undefined",
      name: "string | undefined",
      width: "number | undefined",
      height: "number | undefined",
      allow: "string | undefined",
      allowfullscreen: "boolean | undefined",
      loading: "'lazy' | 'eager' | undefined",
      referrerpolicy:
        "'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url' | undefined",
      sandbox: "string | undefined",
    },
    innerHTML: { include: [] },
    cssPseudoClass: [":fullscreen"],
    cssPseudoElement: [],
  },
  img: {
    display: "inline",
    attributes: {
      src: "`https://${string}` | `http://${string}` | `./${string}` | `/${string}`",
      alt: "string",
      width: "number | undefined",
      height: "number | undefined",
      loading: "'lazy' | 'eager' | undefined",
      srcset: "string | undefined",
      sizes: "string | undefined",
      crossorigin: "'anonymous' | 'use-credentials' | undefined",
      decoding: "'sync' | 'async' | 'auto' | undefined",
      fetchpriority: "'high' | 'low' | 'auto' | undefined",
      ismap: "boolean | undefined",
      usemap: "string | undefined",
      referrerpolicy:
        "'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url' | undefined",
    },
    innerHTML: { include: [] },
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  picture: {
    display: "inline",
    attributes: {},
    innerHTML: { include: ["source", "img"] },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  source: {
    display: "inline",
    attributes: {
      src: "`https://${string}` | `http://${string}` | `./${string}` | `/${string}`",
      srcset: "string | undefined",
      sizes: "string | undefined",
      type: "string | undefined",
      media: "string | undefined",
      width: "number | undefined",
      height: "number | undefined",
    },
    innerHTML: { include: [] },
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  track: {
    display: "inline",
    attributes: {
      kind: {
        subtitles: {
          srclang: "string | undefined",
          label: "string | undefined",
          default: "boolean | undefined",
        },
        captions: {
          label: "string | undefined",
          default: "boolean | undefined",
        },
        descriptions: {
          label: "string | undefined",
          default: "boolean | undefined",
        },
        chapters: {
          label: "string | undefined",
          default: "boolean | undefined",
        },
        metadata: {},
        undefined: {
          srclang: "string | undefined",
          label: "string | undefined",
          default: "boolean | undefined",
        },
      },
      src: "`https://${string}` | `http://${string}` | `./${string}` | `/${string}`",
    },
    innerHTML: { include: [] },
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  video: {
    display: "inline",
    attributes: {
      src: "`https://${string}` | `http://${string}` | `./${string}` | `/${string}`",
      controls: "boolean | undefined",
      autoplay: "boolean | undefined",
      loop: "boolean | undefined",
      muted: "boolean | undefined",
      preload: "'none' | 'metadata' | 'auto' | undefined",
      width: "number | undefined",
      height: "number | undefined",
      poster: "string | undefined",
      playsinline: "boolean | undefined",
    },
    innerHTML: { include: ["source", "track"] },
    cssPseudoClass: [
      ":playing",
      ":paused",
      ":muted",
      ":volume-locked",
      ":seeking",
      ":buffering",
      ":stalled",
      ":picture-in-picture",
    ],
    cssPseudoElement: ["::cue"],
  },

  button: {
    display: "inline-block",
    attributes: {
      type: {
        submit: {
          formaction: "string | undefined",
          formenctype:
            "'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain' | undefined",
          formmethod: "'get' | 'post' | 'dialog' | undefined",
          formnovalidate: "boolean | undefined",
          formtarget: "'_self' | '_blank' | '_parent' | '_top' | undefined",
        },
        reset: {},
        button: {},
        undefined: {
          formaction: "string | undefined",
          formenctype:
            "'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain' | undefined",
          formmethod: "'get' | 'post' | 'dialog' | undefined",
          formnovalidate: "boolean | undefined",
          formtarget: "'_self' | '_blank' | '_parent' | '_top' | undefined",
        },
      },
      disabled: "boolean | undefined",
      name: "string | undefined",
      value: "string | undefined",
      form: "string | undefined",
      popovertarget: "string | undefined",
      popovertargetaction: "'show' | 'hide' | 'toggle' | undefined",
    },
    innerHTML: {
      include: [
        "#text",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "img",
        "ins",
        "kbd",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [":disabled", ":enabled", ":default"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  datalist: {
    display: "inline",
    attributes: {},
    innerHTML: { include: ["option"] },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  fieldset: {
    display: "block",
    attributes: {
      disabled: "boolean | undefined",
      form: "string | undefined",
      name: "string | undefined",
    },
    innerHTML: { include: ["legend", "div", "p", "input", "label", "select", "textarea"] },
    cssPseudoClass: [":disabled"],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  form: {
    display: "block",
    attributes: {
      action: "string | undefined",
      method: {
        get: {
          target: "'_self' | '_blank' | '_parent' | '_top' | undefined",
          novalidate: "boolean | undefined",
        },
        post: {
          enctype:
            "'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain' | undefined",
          target: "'_self' | '_blank' | '_parent' | '_top' | undefined",
          novalidate: "boolean | undefined",
        },
        dialog: {},
      },
      autocomplete: "'on' | 'off' | undefined",
      name: "string | undefined",
      rel: "string | undefined",
    },
    innerHTML: { all: true },
    cssPseudoClass: [":valid", ":invalid", ":user-invalid"],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  input: {
    display: "inline-block",
    attributes: {
      type: {
        text: {
            maxlength: "number | undefined",
            minlength: "number | undefined",
            pattern: "string | undefined",
            size: "number | undefined",
          },
        number: {
            min: "string | number | undefined",
            max: "string | number | undefined",
            step: "string | number | undefined",
          },
        password: {
            maxlength: "number | undefined",
            minlength: "number | undefined",
            pattern: "string | undefined",
            size: "number | undefined",
          },
        checkbox: { checked: "boolean | undefined" },
        radio: { checked: "boolean | undefined" },
        submit: {
            formaction: "string | undefined",
            formenctype:
              "'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain' | undefined",
            formmethod: "'get' | 'post' | 'dialog' | undefined",
            formnovalidate: "boolean | undefined",
            formtarget: "'_self' | '_blank' | '_parent' | '_top' | undefined",
          },
        button: {
            formaction: "string | undefined",
            formenctype:
              "'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain' | undefined",
            formmethod: "'get' | 'post' | 'dialog' | undefined",
            formnovalidate: "boolean | undefined",
            formtarget: "'_self' | '_blank' | '_parent' | '_top' | undefined",
          },
        email: {
            maxlength: "number | undefined",
            minlength: "number | undefined",
            pattern: "string | undefined",
            size: "number | undefined",
            multiple: "boolean | undefined",
          },
        hidden: {},
        file: {
            accept: "string | undefined",
            capture: "'user' | 'environment' | undefined",
            multiple: "boolean | undefined",
          },
        date: {
            min: "string | number | undefined",
            max: "string | number | undefined",
            step: "string | number | undefined",
          },
        time: {
            min: "string | number | undefined",
            max: "string | number | undefined",
            step: "string | number | undefined",
          },
        "datetime-local": {
            min: "string | number | undefined",
            max: "string | number | undefined",
            step: "string | number | undefined",
          },
        month: {
            min: "string | number | undefined",
            max: "string | number | undefined",
            step: "string | number | undefined",
          },
        week: {
            min: "string | number | undefined",
            max: "string | number | undefined",
            step: "string | number | undefined",
          },
        color: {},
        range: {
            min: "string | number | undefined",
            max: "string | number | undefined",
            step: "string | number | undefined",
          },
        search: {
            maxlength: "number | undefined",
            minlength: "number | undefined",
            pattern: "string | undefined",
            size: "number | undefined",
          },
        tel: {
            maxlength: "number | undefined",
            minlength: "number | undefined",
            pattern: "string | undefined",
            size: "number | undefined",
          },
        url: {
            maxlength: "number | undefined",
            minlength: "number | undefined",
            pattern: "string | undefined",
            size: "number | undefined",
          },
        image: {
            src: "`https://${string}` | `http://${string}` | `./${string}` | `/${string}`",
            alt: "string | undefined",
            height: "number | undefined",
            width: "number | undefined",
            formaction: "string | undefined",
            formenctype:
              "'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain' | undefined",
            formmethod: "'get' | 'post' | 'dialog' | undefined",
            formnovalidate: "boolean | undefined",
            formtarget: "'_self' | '_blank' | '_parent' | '_top' | undefined",
          },
        reset: {
            formaction: "string | undefined",
            formenctype:
              "'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain' | undefined",
            formmethod: "'get' | 'post' | 'dialog' | undefined",
            formnovalidate: "boolean | undefined",
            formtarget: "'_self' | '_blank' | '_parent' | '_top' | undefined",
          },
      },
      value: "string | undefined",
      name: "string | undefined",
      placeholder: "string | undefined",
      disabled: "boolean | undefined",
      required: "boolean | undefined",
      readonly: "boolean | undefined",
      hidden: "boolean | undefined",
      autocomplete: "string | undefined",
      autofocus: "boolean | undefined",
      form: "string | undefined",
      list: "string | undefined",
      dirname: "string | undefined",
      popovertarget: "string | undefined",
      popovertargetaction: "'show' | 'hide' | 'toggle' | undefined",
    },
    innerHTML: { include: [] },
    cssPseudoClass: [
      ":disabled",
      ":enabled",
      ":checked",
      ":indeterminate",
      ":default",
      ":valid",
      ":invalid",
      ":in-range",
      ":out-of-range",
      ":required",
      ":optional",
      ":placeholder-shown",
      ":user-invalid",
      ":autofill",
    ],
    cssPseudoElement: ["::placeholder", "::file-selector-button"],
  },
  label: {
    display: "inline",
    attributes: {
      for: "string | undefined",
      form: "string | undefined",
    },
    innerHTML: {
      include: [
        "#text",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "img",
        "input",
        "ins",
        "kbd",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  legend: {
    display: "block",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "hgroup",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  meter: {
    display: "inline-block",
    attributes: {
      value: "number",
      min: "number | undefined",
      max: "number | undefined",
      low: "number | undefined",
      high: "number | undefined",
      optimum: "number | undefined",
      form: "string | undefined",
    },
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [":valid", ":invalid", ":in-range", ":out-of-range"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  optgroup: {
    display: "block",
    attributes: {
      label: "string",
      disabled: "boolean | undefined",
    },
    innerHTML: { include: ["option"] },
    cssPseudoClass: [":disabled"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  option: {
    display: "block",
    attributes: {
      value: "string | undefined",
      label: "string | undefined",
      disabled: "boolean | undefined",
      selected: "boolean | undefined",
    },
    innerHTML: { include: ["#text"] },
    cssPseudoClass: [":disabled", ":checked", ":default"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  output: {
    display: "inline",
    attributes: {
      for: "string | undefined",
      form: "string | undefined",
      name: "string | undefined",
    },
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  progress: {
    display: "inline-block",
    attributes: {
      value: "number | undefined",
      max: "number | undefined",
    },
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [":indeterminate"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  select: {
    display: "inline-block",
    attributes: {
      name: "string | undefined",
      disabled: "boolean | undefined",
      required: "boolean | undefined",
      multiple: "boolean | undefined",
      size: "number | undefined",
      form: "string | undefined",
      autocomplete: "string | undefined",
      autofocus: "boolean | undefined",
    },
    innerHTML: { include: ["option", "optgroup"] },
    cssPseudoClass: [
      ":disabled",
      ":enabled",
      ":valid",
      ":invalid",
      ":required",
      ":optional",
    ],
    cssPseudoElement: [],
  },
  textarea: {
    display: "inline-block",
    attributes: {
      name: "string | undefined",
      placeholder: "string | undefined",
      rows: "number | undefined",
      cols: "number | undefined",
      disabled: "boolean | undefined",
      required: "boolean | undefined",
      readonly: "boolean | undefined",
      maxlength: "number | undefined",
      minlength: "number | undefined",
      autofocus: "boolean | undefined",
      autocomplete: "string | undefined",
      form: "string | undefined",
      dirname: "string | undefined",
      wrap: "'hard' | 'soft' | undefined",
      spellcheck: "boolean | 'default' | undefined",
    },
    innerHTML: { include: ["#text"] },
    cssPseudoClass: [
      ":disabled",
      ":enabled",
      ":valid",
      ":invalid",
      ":required",
      ":optional",
      ":placeholder-shown",
      ":user-invalid",
    ],
    cssPseudoElement: ["::placeholder"],
  },

  caption: {
    display: "table-caption",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  col: {
    display: "table-column",
    attributes: {
      span: "number | undefined",
    },
    innerHTML: { include: [] },
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  colgroup: {
    display: "table-column-group",
    attributes: {
      span: "number | undefined",
    },
    innerHTML: { include: ["col"] },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  table: {
    display: "table",
    attributes: {},
    innerHTML: { include: ["caption", "colgroup", "thead", "tbody", "tfoot", "tr"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  tbody: {
    display: "table-row-group",
    attributes: {},
    innerHTML: { include: ["tr"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  td: {
    display: "table-cell",
    attributes: {
      colspan: "number | undefined",
      rowspan: "number | undefined",
      headers: "string | undefined",
    },
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  tfoot: {
    display: "table-footer-group",
    attributes: {},
    innerHTML: { include: ["tr"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  th: {
    display: "table-cell",
    attributes: {
      colspan: "number | undefined",
      rowspan: "number | undefined",
      headers: "string | undefined",
      scope: "'row' | 'col' | 'rowgroup' | 'colgroup' | undefined",
      abbr: "string | undefined",
    },
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  thead: {
    display: "table-header-group",
    attributes: {},
    innerHTML: { include: ["tr"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  tr: {
    display: "table-row",
    attributes: {},
    innerHTML: { include: ["th", "td"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },

  del: {
    display: "inline",
    attributes: {
      cite: "string | undefined",
      datetime: "string | undefined",
    },
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  ins: {
    display: "inline",
    attributes: {
      cite: "string | undefined",
      datetime: "string | undefined",
    },
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  pre: {
    display: "block",
    attributes: {},
    innerHTML: {
      include: [
        "#text",
        "a",
        "abbr",
        "audio",
        "b",
        "bdi",
        "bdo",
        "br",
        "button",
        "canvas",
        "cite",
        "code",
        "data",
        "datalist",
        "del",
        "dfn",
        "em",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "mark",
        "meter",
        "output",
        "picture",
        "progress",
        "q",
        "ruby",
        "s",
        "samp",
        "select",
        "slot",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "template",
        "textarea",
        "time",
        "u",
        "var",
        "video",
        "wbr",
      ],
    },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  slot: {
    display: "contents",
    attributes: {
      name: "string | undefined",
    },
    innerHTML: { all: true },
    cssPseudoClass: [":slotted()"],
    cssPseudoElement: ["::before", "::after", "::selection", "::slotted()"],
  },
  template: {
    display: "none",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
});
