import { SUPPORTED_KEYWORDS } from "@/dsl/index.ts";
import { htmlTagConfig } from "../index.ts";

export default htmlTagConfig(SUPPORTED_KEYWORDS, {
  // ─── Text & Inline ─────────────────────────────────────────────────
  a: {
    attributes: {
      href: "string | undefined",
      target: "'_self' | '_blank' | '_parent' | '_top' | undefined",
      download: "string | boolean | undefined",
      rel: "string | undefined",
      hreflang: "string | undefined",
      ping: "string | undefined",
      referrerpolicy:
        "'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url' | undefined",
    },
    innerHTML: [
      "#text",
      "img",
      "div",
      "section",
      "p",
      "ul",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "span",
      "abbr",
      "cite",
      "code",
      "em",
      "strong",
      "time",
    ],
    cssPseudoClass: [":link", ":visited", ":any-link", ":local-link"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  abbr: {
    attributes: {
      title: "string | undefined",
    },
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  address: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  b: {
    attributes: {},
    innerHTML: ["#text", "span", "a", "em", "strong"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  bdi: {
    attributes: {
      dir: "'ltr' | 'rtl' | 'auto' | undefined",
    },
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  bdo: {
    attributes: {
      dir: "'ltr' | 'rtl'",
    },
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  blockquote: {
    attributes: {
      cite: "string | undefined",
    },
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  br: {
    attributes: {},
    innerHTML: [],
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  cite: {
    attributes: {},
    innerHTML: ["#text", "a"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  code: {
    attributes: {},
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  data: {
    attributes: {
      value: "string",
    },
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  dfn: {
    attributes: {
      title: "string | undefined",
    },
    innerHTML: ["#text", "abbr"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  em: {
    attributes: {},
    innerHTML: ["#text", "span", "a", "strong"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  i: {
    attributes: {},
    innerHTML: ["#text", "span"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  kbd: {
    attributes: {},
    innerHTML: ["#text", "kbd"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  mark: {
    attributes: {},
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  q: {
    attributes: {
      cite: "string | undefined",
    },
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  rp: {
    attributes: {},
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  rt: {
    attributes: {},
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  ruby: {
    attributes: {},
    innerHTML: ["#text", "rp", "rt"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  s: {
    attributes: {},
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  samp: {
    attributes: {},
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  small: {
    attributes: {},
    innerHTML: ["#text", "span"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  span: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  strong: {
    attributes: {},
    innerHTML: ["#text", "span", "a", "em"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  sub: {
    attributes: {},
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  sup: {
    attributes: {},
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  time: {
    attributes: {
      datetime: "string | undefined",
    },
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  u: {
    attributes: {},
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  var: {
    attributes: {},
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  wbr: {
    attributes: {},
    innerHTML: [],
    cssPseudoClass: [],
    cssPseudoElement: [],
  },

  // ─── Headings ──────────────────────────────────────────────────────
  h1: {
    attributes: {},
    innerHTML: ["#text", "span", "a", "em", "strong", "small", "abbr"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  h2: {
    attributes: {},
    innerHTML: ["#text", "span", "a", "em", "strong", "small", "abbr"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  h3: {
    attributes: {},
    innerHTML: ["#text", "span", "a", "em", "strong", "small", "abbr"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  h4: {
    attributes: {},
    innerHTML: ["#text", "span", "a", "em", "strong", "small", "abbr"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  h5: {
    attributes: {},
    innerHTML: ["#text", "span", "a", "em", "strong", "small", "abbr"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  h6: {
    attributes: {},
    innerHTML: ["#text", "span", "a", "em", "strong", "small", "abbr"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  hgroup: {
    attributes: {},
    innerHTML: ["h1", "h2", "h3", "h4", "h5", "h6", "p"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },

  // ─── Sectioning & Layout ───────────────────────────────────────────
  article: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  aside: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  details: {
    attributes: {
      open: "boolean | undefined",
    },
    innerHTML: ["summary", "div", "p", "ul", "ol", "table"],
    cssPseudoClass: [":open"],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection", "::details-content"],
  },
  dialog: {
    attributes: {
      open: "boolean | undefined",
    },
    innerHTML: "*",
    cssPseudoClass: [":open", ":modal"],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection", "::backdrop"],
  },
  div: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  footer: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  header: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  main: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  nav: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  p: {
    attributes: {},
    innerHTML: [
      "#text",
      "span",
      "a",
      "img",
      "input",
      "br",
      "label",
      "abbr",
      "b",
      "cite",
      "code",
      "em",
      "i",
      "kbd",
      "mark",
      "q",
      "s",
      "samp",
      "small",
      "strong",
      "sub",
      "sup",
      "time",
      "u",
      "var",
      "wbr",
    ],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  search: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  section: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  summary: {
    attributes: {},
    innerHTML: ["#text", "span", "a", "em", "strong"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection", "::marker"],
  },

  // ─── Lists ─────────────────────────────────────────────────────────
  dd: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  dl: {
    attributes: {},
    innerHTML: ["dt", "dd"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  dt: {
    attributes: {},
    innerHTML: ["#text", "span", "a", "abbr", "em", "strong"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  li: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection", "::marker"],
  },
  menu: {
    attributes: {},
    innerHTML: ["li"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  ol: {
    attributes: {
      reversed: "boolean | undefined",
      start: "number | undefined",
      type: "'1' | 'a' | 'A' | 'i' | 'I' | undefined",
    },
    innerHTML: ["li"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  ul: {
    attributes: {},
    innerHTML: ["li"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },

  // ─── Media ─────────────────────────────────────────────────────────
  audio: {
    attributes: {
      src: "string | undefined",
      controls: "boolean | undefined",
      autoplay: "boolean | undefined",
      loop: "boolean | undefined",
      muted: "boolean | undefined",
      preload: "'none' | 'metadata' | 'auto' | undefined",
    },
    innerHTML: ["source", "track"],
    cssPseudoClass: [
      ":playing",
      ":paused",
      ":muted",
      ":volume-locked",
      ":seeking",
      ":buffering",
      ":stalled",
    ],
    cssPseudoElement: [],
  },
  canvas: {
    attributes: {
      width: "number | undefined",
      height: "number | undefined",
    },
    innerHTML: ["#text"],
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  figcaption: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  figure: {
    attributes: {},
    innerHTML: ["img", "video", "audio", "canvas", "picture", "figcaption"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  iframe: {
    attributes: {
      src: "string | undefined",
      srcdoc: "string | undefined",
      name: "string | undefined",
      width: "number | undefined",
      height: "number | undefined",
      allow: "string | undefined",
      allowfullscreen: "boolean | undefined",
      loading: "'lazy' | 'eager' | undefined",
      referrerpolicy:
        "'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url' | undefined",
      sandbox: "string | undefined",
    },
    innerHTML: [],
    cssPseudoClass: [":fullscreen"],
    cssPseudoElement: [],
  },
  img: {
    attributes: {
      src: "string",
      alt: "string",
      width: "number | undefined",
      height: "number | undefined",
      loading: "'lazy' | 'eager' | undefined",
      srcset: "string | undefined",
      sizes: "string | undefined",
      crossorigin: "'anonymous' | 'use-credentials' | undefined",
      decoding: "'sync' | 'async' | 'auto' | undefined",
      fetchpriority: "'high' | 'low' | 'auto' | undefined",
      ismap: "boolean | undefined",
      usemap: "string | undefined",
      referrerpolicy:
        "'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url' | undefined",
    },
    innerHTML: [],
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  picture: {
    attributes: {},
    innerHTML: ["source", "img"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  source: {
    attributes: {
      src: "string | undefined",
      srcset: "string | undefined",
      sizes: "string | undefined",
      type: "string | undefined",
      media: "string | undefined",
      width: "number | undefined",
      height: "number | undefined",
    },
    innerHTML: [],
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  track: {
    attributes: {
      kind: "'subtitles' | 'captions' | 'descriptions' | 'chapters' | 'metadata' | undefined",
      src: "string",
      srclang: "string | undefined",
      label: "string | undefined",
      default: "boolean | undefined",
    },
    innerHTML: [],
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  video: {
    attributes: {
      src: "string | undefined",
      controls: "boolean | undefined",
      autoplay: "boolean | undefined",
      loop: "boolean | undefined",
      muted: "boolean | undefined",
      preload: "'none' | 'metadata' | 'auto' | undefined",
      width: "number | undefined",
      height: "number | undefined",
      poster: "string | undefined",
      playsinline: "boolean | undefined",
    },
    innerHTML: ["source", "track"],
    cssPseudoClass: [
      ":playing",
      ":paused",
      ":muted",
      ":volume-locked",
      ":seeking",
      ":buffering",
      ":stalled",
      ":picture-in-picture",
    ],
    cssPseudoElement: ["::cue"],
  },

  // ─── Forms ─────────────────────────────────────────────────────────
  button: {
    attributes: {
      type: "'submit' | 'reset' | 'button' | undefined",
      disabled: "boolean | undefined",
      name: "string | undefined",
      value: "string | undefined",
      form: "string | undefined",
      formaction: "string | undefined",
      formenctype:
        "'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain' | undefined",
      formmethod: "'get' | 'post' | 'dialog' | undefined",
      formnovalidate: "boolean | undefined",
      formtarget: "'_self' | '_blank' | '_parent' | '_top' | undefined",
      popovertarget: "string | undefined",
      popovertargetaction: "'show' | 'hide' | 'toggle' | undefined",
    },
    innerHTML: ["#text", "span", "img", "em", "strong"],
    cssPseudoClass: [":disabled", ":enabled", ":default"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  datalist: {
    attributes: {},
    innerHTML: ["option"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  fieldset: {
    attributes: {
      disabled: "boolean | undefined",
      form: "string | undefined",
      name: "string | undefined",
    },
    innerHTML: ["legend", "div", "p", "input", "label", "select", "textarea"],
    cssPseudoClass: [":disabled"],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  form: {
    attributes: {
      action: "string",
      method: "'get' | 'post' | 'dialog'",
      enctype:
        "'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain' | undefined",
      novalidate: "boolean | undefined",
      target: "'_self' | '_blank' | '_parent' | '_top' | undefined",
      autocomplete: "'on' | 'off' | undefined",
      name: "string | undefined",
      rel: "string | undefined",
    },
    innerHTML: "*",
    cssPseudoClass: [":valid", ":invalid", ":user-invalid"],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  input: {
    attributes: {
      type: "'text' | 'number' | 'password' | 'checkbox' | 'radio' | 'submit' | 'button' | 'email' | 'hidden' | 'file' | 'date' | 'time' | 'datetime-local' | 'month' | 'week' | 'color' | 'range' | 'search' | 'tel' | 'url' | 'image' | 'reset'",
      value: "string",
      checked: "boolean | undefined",
      name: "string | undefined",
      placeholder: "string | undefined",
      disabled: "boolean | undefined",
      required: "boolean | undefined",
      readonly: "boolean | undefined",
      maxlength: "number | undefined",
      minlength: "number | undefined",
      max: "string | number | undefined",
      min: "string | number | undefined",
      step: "string | number | undefined",
      pattern: "string | undefined",
      hidden: "boolean | undefined",
      autocomplete: "string | undefined",
      autofocus: "boolean | undefined",
      form: "string | undefined",
      list: "string | undefined",
      multiple: "boolean | undefined",
      size: "number | undefined",
      accept: "string | undefined",
      capture: "'user' | 'environment' | undefined",
      dirname: "string | undefined",
      formaction: "string | undefined",
      formenctype:
        "'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain' | undefined",
      formmethod: "'get' | 'post' | 'dialog' | undefined",
      formnovalidate: "boolean | undefined",
      formtarget: "'_self' | '_blank' | '_parent' | '_top' | undefined",
      height: "number | undefined",
      width: "number | undefined",
      src: "string | undefined",
      alt: "string | undefined",
      popovertarget: "string | undefined",
      popovertargetaction: "'show' | 'hide' | 'toggle' | undefined",
    },
    innerHTML: [],
    cssPseudoClass: [
      ":disabled",
      ":enabled",
      ":checked",
      ":indeterminate",
      ":default",
      ":valid",
      ":invalid",
      ":in-range",
      ":out-of-range",
      ":required",
      ":optional",
      ":placeholder-shown",
      ":user-invalid",
      ":autofill",
    ],
    cssPseudoElement: ["::placeholder", "::file-selector-button"],
  },
  label: {
    attributes: {
      for: "string | undefined",
      form: "string | undefined",
    },
    innerHTML: ["#text", "input", "span", "img", "abbr", "em", "strong"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  legend: {
    attributes: {},
    innerHTML: ["#text", "span", "a", "label"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  meter: {
    attributes: {
      value: "number",
      min: "number | undefined",
      max: "number | undefined",
      low: "number | undefined",
      high: "number | undefined",
      optimum: "number | undefined",
      form: "string | undefined",
    },
    innerHTML: ["#text"],
    cssPseudoClass: [":valid", ":invalid", ":in-range", ":out-of-range"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  optgroup: {
    attributes: {
      label: "string",
      disabled: "boolean | undefined",
    },
    innerHTML: ["option"],
    cssPseudoClass: [":disabled"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  option: {
    attributes: {
      value: "string | undefined",
      label: "string | undefined",
      disabled: "boolean | undefined",
      selected: "boolean | undefined",
    },
    innerHTML: ["#text"],
    cssPseudoClass: [":disabled", ":checked", ":default"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  output: {
    attributes: {
      for: "string | undefined",
      form: "string | undefined",
      name: "string | undefined",
    },
    innerHTML: ["#text", "span"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  progress: {
    attributes: {
      value: "number | undefined",
      max: "number | undefined",
    },
    innerHTML: ["#text"],
    cssPseudoClass: [":indeterminate"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  select: {
    attributes: {
      name: "string | undefined",
      disabled: "boolean | undefined",
      required: "boolean | undefined",
      multiple: "boolean | undefined",
      size: "number | undefined",
      form: "string | undefined",
      autocomplete: "string | undefined",
      autofocus: "boolean | undefined",
    },
    innerHTML: ["option", "optgroup"],
    cssPseudoClass: [
      ":disabled",
      ":enabled",
      ":valid",
      ":invalid",
      ":required",
      ":optional",
    ],
    cssPseudoElement: [],
  },
  textarea: {
    attributes: {
      name: "string | undefined",
      value: "string",
      placeholder: "string | undefined",
      rows: "number | undefined",
      cols: "number | undefined",
      disabled: "boolean | undefined",
      required: "boolean | undefined",
      readonly: "boolean | undefined",
      maxlength: "number | undefined",
      minlength: "number | undefined",
      autofocus: "boolean | undefined",
      autocomplete: "string | undefined",
      form: "string | undefined",
      dirname: "string | undefined",
      wrap: "'hard' | 'soft' | undefined",
      spellcheck: "boolean | 'default' | undefined",
    },
    innerHTML: ["#text"],
    cssPseudoClass: [
      ":disabled",
      ":enabled",
      ":valid",
      ":invalid",
      ":required",
      ":optional",
      ":placeholder-shown",
      ":user-invalid",
    ],
    cssPseudoElement: ["::placeholder"],
  },

  // ─── Tables ─────────────────────────────────────────────────────────
  caption: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  col: {
    attributes: {
      span: "number | undefined",
    },
    innerHTML: [],
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  colgroup: {
    attributes: {
      span: "number | undefined",
    },
    innerHTML: ["col"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  table: {
    attributes: {},
    innerHTML: ["caption", "colgroup", "thead", "tbody", "tfoot", "tr"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  tbody: {
    attributes: {},
    innerHTML: ["tr"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  td: {
    attributes: {
      colspan: "number | undefined",
      rowspan: "number | undefined",
      headers: "string | undefined",
    },
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  tfoot: {
    attributes: {},
    innerHTML: ["tr"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  th: {
    attributes: {
      colspan: "number | undefined",
      rowspan: "number | undefined",
      headers: "string | undefined",
      scope: "'row' | 'col' | 'rowgroup' | 'colgroup' | undefined",
      abbr: "string | undefined",
    },
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  thead: {
    attributes: {},
    innerHTML: ["tr"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  tr: {
    attributes: {},
    innerHTML: ["th", "td"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },

  // ─── Interactive & Scripting ────────────────────────────────────────
  del: {
    attributes: {
      cite: "string | undefined",
      datetime: "string | undefined",
    },
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  ins: {
    attributes: {
      cite: "string | undefined",
      datetime: "string | undefined",
    },
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  pre: {
    attributes: {},
    innerHTML: ["#text", "code", "samp", "kbd"],
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::first-letter", "::first-line", "::selection"],
  },
  slot: {
    attributes: {
      name: "string | undefined",
    },
    innerHTML: "*",
    cssPseudoClass: [":slotted()"],
    cssPseudoElement: ["::before", "::after", "::selection", "::slotted()"],
  },
  template: {
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
});
