import { SUPPORTED_KEYWORDS } from "@/dsl/index.ts";
import { htmlTagConfig } from "@/html/tag-config/index.ts";
import CSS_ATTRIBUTES_CONFIG from "@/css/attribute-config/variations/minimal.ts";

export default htmlTagConfig(SUPPORTED_KEYWORDS, CSS_ATTRIBUTES_CONFIG, {
  a: {
    display: "inline",
    attributes: {
      href: "string",
      target: "'_self' | '_blank' | undefined",
    },
    innerHTML: [
      "#text",
      "img",
      "div",
      "p",
      "ul",
      "h1",
      "h2",
      "h3",
      "span",
      "br",
    ],
    cssPseudoClass: [":link", ":visited"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  br: {
    display: "inline",
    attributes: {},
    innerHTML: [],
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  button: {
    display: "inline-block",
    attributes: {
      type: "'submit' | 'reset' | 'button' | undefined",
      disabled: "boolean | undefined",
    },
    innerHTML: ["#text", "span", "br", "img"],
    cssPseudoClass: [":disabled"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  div: {
    display: "block",
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h1: {
    display: "block",
    attributes: {},
    innerHTML: ["#text", "span", "a", "br", "img"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h2: {
    display: "block",
    attributes: {},
    innerHTML: ["#text", "span", "a", "br", "img"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h3: {
    display: "block",
    attributes: {},
    innerHTML: ["#text", "span", "a", "br", "img"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  img: {
    display: "inline",
    attributes: {
      src: "string",
      alt: "string",
    },
    innerHTML: [],
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  input: {
    display: "inline-block",
    attributes: {
      type: "'text' | 'number' | 'password' | 'checkbox' | 'radio' | 'submit' | 'hidden'",
      value: "string | undefined",
      disabled: "boolean | undefined",
    },
    innerHTML: [],
    cssPseudoClass: [":disabled", ":checked"],
    cssPseudoElement: ["::placeholder", "::file-selector-button"],
  },
  li: {
    display: "list-item",
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
      "::marker",
    ],
  },
  p: {
    display: "block",
    attributes: {},
    innerHTML: ["#text", "span", "a", "br", "img"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  span: {
    display: "inline",
    attributes: {},
    innerHTML: "*",
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  ul: {
    display: "block",
    attributes: {},
    innerHTML: ["li"],
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
});
