import { SUPPORTED_KEYWORDS } from "tsyntax";
import { htmlTagConfig } from "@/html/tag-config/index.ts";
import CSS_ATTRIBUTES_CONFIG from "@/css/attribute-config/variations/minimal.ts";

export default htmlTagConfig(SUPPORTED_KEYWORDS, CSS_ATTRIBUTES_CONFIG, {
  a: {
    display: "inline",
    attributes: {
      href: "`https://${string}` | `http://${string}` | `mailto:${string}` | `tel:${string}` | `./${string}` | `/${string}`",
      target: "'_self' | '_blank' | undefined",
    },
    innerHTML: {
      include: [
        "#text",
        "img",
        "div",
        "p",
        "ul",
        "h1",
        "h2",
        "h3",
        "span",
        "br",
      ],
    },
    cssPseudoClass: [":link", ":visited"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  br: {
    display: "inline",
    attributes: {},
    innerHTML: { include: [] },
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  button: {
    display: "inline-block",
    attributes: {
      type: "'submit' | 'reset' | 'button' | undefined",
      disabled: "boolean | undefined",
    },
    innerHTML: { include: ["#text", "span", "br", "img"] },
    cssPseudoClass: [":disabled"],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  div: {
    display: "block",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h1: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["#text", "span", "a", "br", "img"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h2: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["#text", "span", "a", "br", "img"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  h3: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["#text", "span", "a", "br", "img"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  img: {
    display: "inline",
    attributes: {
      href: "`https://${string}` | `http://${string}` | `mailto:${string}` | `tel:${string}` | `./${string}` | `/${string}`",
      alt: "string",
    },
    innerHTML: { include: [] },
    cssPseudoClass: [],
    cssPseudoElement: [],
  },
  input: {
    display: "inline-block",
    attributes: {
      type: {
        text: {},
        number: {},
        password: {},
        checkbox: { checked: "boolean | undefined" },
        radio: { checked: "boolean | undefined" },
        submit: {},
        hidden: {},
      },
      value: "string | undefined",
      disabled: "boolean | undefined",
    },
    innerHTML: { include: [] },
    cssPseudoClass: [":disabled", ":checked"],
    cssPseudoElement: ["::placeholder", "::file-selector-button"],
  },
  li: {
    display: "list-item",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
      "::marker",
    ],
  },
  p: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["#text", "span", "a", "br", "img"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
  span: {
    display: "inline",
    attributes: {},
    innerHTML: { all: true },
    cssPseudoClass: [],
    cssPseudoElement: ["::before", "::after", "::selection"],
  },
  ul: {
    display: "block",
    attributes: {},
    innerHTML: { include: ["li"] },
    cssPseudoClass: [],
    cssPseudoElement: [
      "::before",
      "::after",
      "::first-letter",
      "::first-line",
      "::selection",
    ],
  },
});
